#pragma once

#define MAIN_Version "bfd7c45"
#define KNX_Version "2.2.1+1b646c1"
#define MODULE_FileTransferModule_Version "0.1.1+4be8e34"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 1
#define MODULE_FileTransferModule_ETS 1
#define MODULE_Common_Version "1.4.3+b286293"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 4
#define MODULE_Common_Version_Revision 3
#define MODULE_Common_ETS 20
#define MODULE_LogicModule_Version "3.7.1+5e30d8d"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 7
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 55
#define MODULE_PowerAmp_Version "3675323"
#define MODULE_SwitchActuator_Version "0.1.0+c35288a"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
#define MODULE_UsbExchange_Version "0.0.1+0411a9d"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 1
#define MODULE_UsbExchange_ETS 0
#define MODULE_DFA_Version "0.5.0+d700ed6"
#define MODULE_DFA_Version_Major 0
#define MODULE_DFA_Version_Minor 5
#define MODULE_DFA_Version_Revision 0
#define MODULE_DFA_ETS 5
